server:
  port: 8083

spring:
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: microservices

  application:
    name: RATING-SERVICE
eureka:
   instance:
     prefer-ip-address: true
   client:
     fetch-registry: true
     registry-with-eureka: true
     service-url:
       defaultZone: http://localhost:8761/eureka