server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
#            - Path=/users/**,/staffs/** for multiple url/controllers

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


#okta configuration for api gateway
okta:
  oauth2:
    issuer: https://dev-84262907.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaabww0xdzD0KQUJ5d7
    client-secret: wytd73V9pGeJNh4acMZpiG5v0waoNUp98vJ4280V
    scopes: openid, profile, email, offline_access